# Change baseurl before deploy
baseurl = "https://iiloveyou.org"
languageCode = "en-us"
paginate = 5
title = "Hugo Theme Stack Starter"
theme = "hugo-theme-stack"

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "iiloveyou"

# GA Tracking ID
googleAnalytics = ""
